### ISSUE TITLE
Third Color Sensor to auto detect incorrectly colored balls

### ISSUE THREAD

**Issue by Weznon** [0207-Critical-Mass/0207-Velocity-Vortex#19]
This requires another color sensor.

**Comment by Burtorustum** [comment]
We must decide whether we want to auto reject the balls or just show telemetry of the color of ball. Also need to test if it causes delay between the drivers and the robot

**Comment by Burtorustum** [comment]
Completed with full auto rejection for both red and blue in  c7409cc
