### ISSUE TITLE
Add non static movement speeds

### ISSUE THREAD

**Issue by Weznon** [0207-Critical-Mass/0207-Velocity-Vortex#21]
Instead of only setting the speed of motors to 1 or 0, use a double to make slower/faster movement. 

This should be added in `Teleop_Invert.java`, but no testing has been done yet.

**Comment by Weznon** [comment]
Works - Not much difference between max and min, but its good enough

**Comment by Burtorustum** [comment]
According to rob the left side isnt working right now

**Comment by Weznon** [comment]
Commit 8964295 has fixed any issues with this, all of it works
