### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by Weznon** [0207-Critical-Mass/0207-Velocity-Vortex#22]
Currently we have very few useful comments, if there are any comments

This should be fixed

**Comment by Weznon** [comment]
Started work on this in commit 7257305

**Comment by Weznon** [comment]
Rob worked on comments in Bot class and normal teleop in 336839e7eb49c57d899bf189c1194669c9b12ac7

**Comment by Weznon** [comment]
Finished documentation for Teleop_Invert in 10612ee

**Comment by Burtorustum** [comment]
Did the documentation for Auton_RedTwoShots in ffa821f

**Comment by Burtorustum** [comment]
Continued working on Bot class comments in a1a2fde

**Comment by Weznon** [comment]
added documentation for my changes in bot class (so the invert method and servo stuff) in 0f9a268

fixed a slight error in 25a7cf4

**Comment by Burtorustum** [comment]
Continued adding comments to the Bot class in d077022

**Comment by Weznon** [comment]
Closing, I think we'll be fine as long as we continue to comment code
