### ISSUE TITLE
Make strafing gradual

### ISSUE THREAD

**Issue by Burtorustum** [0207-Critical-Mass/0207-Velocity-Vortex#31]
Make it so that the triggers on rob's controller direct input to the power for the strafes. This means when half down = 0.5 power input for strafe etc. Triggers output doubles so this should be simple I think. I'm letting you do this so I don't break the invert stuff. This could make it so the bot doesn't do somersaults when we strafe.

**Comment by Weznon** [comment]
Done, commit d86c55b

**Comment by Weznon** [comment]
Probably should test before closing, though im resonably sure this will work

**Comment by Weznon** [comment]
so that one didnt work, since it only would set the power the first time it detected the button pressed

should be fixed in commit 6a8229b

**Comment by Weznon** [comment]
works as of 8964295
