### ISSUE TITLE
Auton Improvement

### ISSUE THREAD

**Issue by Burtorustum** [0207-Critical-Mass/0207-Velocity-Vortex#35]
- Add Gyro to ensure we don't spin out while strafing / after pressing beacon
- Add Range/ODS/Touch to find if close to wall (Depends on if we are getting a field) 
- Add ODS to find white line
- Add re-check of beacon after initial press to ensure color was changed correctly

**Comment by Lleweg** [comment]
There are 3 givens when trying to hit beacons:

- The starting wall is perpendicular to the beacon wall
- The beacon wall always looks the same
- The inner edge of the beacon wall is always the same distance from the beacon button

Using these we can develop a consistent auton that works even in poor operating conditions. The steps of such an auton would be:

- Line the bot up against the starting wall facing the vortex (parallel to the beacon wall)
- Drive forward and launch 2 balls into the center vortex
- Drive diagonally to the wall, ensure that you remain parallel to the wall using a gyro
- Determine how far you are from the wall using an ODS or range sensor (All walls are the same color, so light should reflect in the same way off of every wall)
- Once approximately 7 centimeters from the wall, begin driving towards the first beacon to be pressed
- Using an ODS sensor, find the white line of the first beacon
- Strafe close to the beacon, use a color sensor to determine which side of the beacon must be pressed
- Press the beacon button by strafing into it
- Strafe away from the beacon, realign robot to be parallel
- Repeat steps 6-9 for the other beacon
- Drive towards the center plate, determine if you are there by checking the ODS sensor normally used for finding the beacon lines
- If there, stop movement and end auton
-

**Comment by Burtorustum** [comment]
Completed enough for our auton to work consistently prior to worlds. Done!
